name: Run Python tests

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:


permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python

    steps:
    - name: Checkout repository
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

    - name: Set up Python
      uses: actions/setup-python@2bd53f9a4d1dd1cd21eaffcc01a7b91a8e73ea4c
      with:
        python-version: '3.x'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r test_requirements.txt

    - name: Run tests
      run: |
        python -m pytest src/tests/ -vv